### PR TITLE
Refactor DNS resolver

### PR DESCRIPTION
**Pull request by crackcomm**
It is not that important but anyway it's better.
I wanted to utilize `gomainr` but I think I'll just use `dnsr` instead so I am just proposing for merge so it won't go to waste although it's not much work :)

Thanks

btw. Config is not used at all?

### CODE REVIEW

**Comment by MichaelThessel** [comment]
I already implemented a cache that works across all sources and saves results for 24hrs. I believe this is a better solution.

https://github.com/crackcomm/gomainr/blob/a059cd43cb8d7edde1e1be8fb1661b7fbff29121/search/search.go#L27

**Comment by crackcomm** [comment]
I think it's better not to construct resolver on every call so maybe just set the cache capacity to 0 in `dnsr.New(0)`?

**Comment by MichaelThessel** [comment]
K. makes sense. Can you update the PR with the change, then I can merge it.

**Comment by crackcomm** [comment]
It's done, in case you missed it :+1:

**Comment by MichaelThessel** [comment]
Merged, thanks!

**Pull request merged**
